language: cpp
before_install:
- sudo apt install mesa-common-dev libglu1-mesa-dev freeglut3-dev libosmesa6-dev cmake libx11-dev xorg-dev libglu1-mesa-dev freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev
before_script: cd gaps

#sudo apt install make g++ mesa-common-dev libglu1-mesa-dev freeglut3-dev libosmesa6-dev
#cmake libx11-dev xorg-dev libglu1-mesa-dev freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev
